services:

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /home/flashsysXXX/homeassistant-compose/config:/config
      - /home/flashsysXXX/data/123XXX_data:/123XXX_data
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    devices:
      - /dev/ttyUSB0
      - /dev/ttyUSB1
    privileged: true
    network_mode: host
