
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

script: !include scripts.yaml
scene: !include scenes.yaml

shell_command:
  bluetoothctl_off: bluetoothctl power off
  bluetoothctl_on: bluetoothctl power on

notify:
  - platform: file
    name: filenotify
    filename: /home/flashsysXXX/data/123XXX_data/123XXX_tv_power_5s.csv
    #timestamp: true
    
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
      - type: memory_use_percent		
      - type: memory_use
      - type: memory_free
      - type: swap_use_percent
      - type: swap_use		
      - type: swap_free
      
automation: 
- alias: Backup TV Power Data from Smart Plug Every 5 Seconds
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    seconds: /5
  action:
  - service: notify.filenotify
    data_template:
      message: '{{states(''sensor.plug_mini_YYYY_power'')}};{{now().strftime(''%m.%d.%Y'')}};
        {{now().strftime(''%H.%M.%S'')}}'
  mode: single
  
- alias: Restart Bluetooth Every 6 Hours
  description: ''
  initial_state: 'on'
  trigger:
  - platform: time_pattern
    hours: /6
  condition: []
  action:
  - service: shell_command.bluetoothctl_off
    data: {}
  - delay:
      hours: 0
      minutes: 0
      seconds: 5
      milliseconds: 0
  - service: shell_command.bluetoothctl_on
    data: {}
  mode: single

